# $ mint run xcodegen generate

name: CatBoard
options:
  deploymentTarget:
    iOS: 16.0
  createIntermediateGroups: true

configs:
  Debug: debug
  Release: release

settings:
  base:
    SWIFT_VERSION: 5.9
    MARKETING_VERSION: 1.0
    CURRENT_PROJECT_VERSION: 1
    ENABLE_USER_SCRIPT_SANDBOXING: "NO"

# signing:
#   automaticSigning:
#     teamID: YOUR_TEAM_ID

packages:
  ScaryCatScreeningKit:
    url: https://github.com/terrio32/scary-cat-screening-kit
    from: "1.3.1"
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    from: "1.19.1"
  Dependencies:
    url: https://github.com/pointfreeco/swift-dependencies
    from: "1.2.0"
  CasePaths:
    url: https://github.com/pointfreeco/swift-case-paths
    from: "1.1.0"
  SwiftNavigation:
    url: https://github.com/pointfreeco/swift-navigation
    from: "2.3.0"
  Clocks:
    url: https://github.com/pointfreeco/swift-clocks
    from: "1.0.0"
  TieredGridLayout:
    url: https://github.com/terrio32/tiered-grid-layout
    from: "1.0.4"
  IdentifiedCollections:
    url: https://github.com/pointfreeco/swift-identified-collections
    from: "1.0.0"
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher.git
    from: "8.3.2"
  # Add other necessary packages for CatBoard here

targets:
  CatBoard:
    type: application
    platform: iOS
    sources:
      - path: CatBoard
    dependencies:
      - target: Infrastructure
      - target: CBShared
      - package: ComposableArchitecture
        product: ComposableArchitecture
      - package: Dependencies
        product: Dependencies
      - package: CasePaths
        product: CasePaths
      - package: SwiftNavigation
        product: SwiftNavigation
      - package: Clocks
        product: Clocks
      - package: TieredGridLayout
        product: TieredGridLayout
      - package: ScaryCatScreeningKit
        product: ScaryCatScreeningKit
      - package: IdentifiedCollections
        product: IdentifiedCollections
      - package: Kingfisher
    settings:
      base:
        DEVELOPMENT_LANGUAGE: ja
        GENERATE_INFOPLIST_FILE: "YES"
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.CatBoard
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        # Add other required iOS settings
    info:
      path: CatBoard/Info.plist
      properties:
        CFBundleName: $(PRODUCT_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleDisplayName: CatBoard
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIStatusBarStyle: UIStatusBarStyleDefault
        UIStatusBarHidden: false
        UIViewControllerBasedStatusBarAppearance: true
        UIRequiresFullScreen: false
        # Add other necessary plist keys

  Infrastructure:
    type: framework
    platform: iOS
    sources:
      - path: Infrastructure
    dependencies:
      - target: CBShared
      - package: ComposableArchitecture
        product: ComposableArchitecture
      - package: ScaryCatScreeningKit
        product: ScaryCatScreeningKit
    settings:
      base:
        DEVELOPMENT_LANGUAGE: ja
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.CatBoard.Infrastructure
        TARGETED_DEVICE_FAMILY: "1,2"
        GENERATE_INFOPLIST_FILE: YES
        SKIP_INSTALL: "NO"

  CBShared:
    type: framework
    platform: iOS
    sources:
      - path: CBShared
    settings:
      base:
        DEVELOPMENT_LANGUAGE: ja
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.CatBoard.CBShared
        TARGETED_DEVICE_FAMILY: "1,2"
        GENERATE_INFOPLIST_FILE: YES
        SKIP_INSTALL: "NO"

  CatBoardTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: CatBoardTests
    dependencies:
      - target: CatBoard
      - target: Infrastructure
      - target: CBShared
      - package: ComposableArchitecture
        product: ComposableArchitecture
      - package: Dependencies
        product: Dependencies
      - package: CasePaths
        product: CasePaths
      - package: SwiftNavigation
        product: SwiftNavigation
      - package: Clocks
        product: Clocks
      - package: IdentifiedCollections
        product: IdentifiedCollections
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.CatBoardTests
        TARGETED_DEVICE_FAMILY: "1,2"
        GENERATE_INFOPLIST_FILE: YES

  CatBoardUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: CatBoardUITests
    dependencies:
      - target: CatBoard
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.CatBoardUITests
        TARGETED_DEVICE_FAMILY: "1,2"
        TEST_TARGET_NAME: CatBoard
        GENERATE_INFOPLIST_FILE: YES

schemes:
  CatBoard:
    build:
      targets:
        CatBoard: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - CatBoardTests
        - CatBoardUITests

  CatBoardTests:
    build:
      targets:
        CatBoardTests: test
    test:
      config: Debug
      targets:
        - CatBoardTests

  CatBoardUITests:
    build:
      targets:
        CatBoardUITests: test
    test:
      config: Debug
      targets:
        - CatBoardUITests
