# $ mint run xcodegen generate

name: CatBoardApp
options:
  deploymentTarget:
    iOS: 17.0
  createIntermediateGroups: true

configs:
  Debug: debug
  Release: release

settings:
  base:
    SWIFT_VERSION: 5.9
    MARKETING_VERSION: 1.0
    CURRENT_PROJECT_VERSION: 1
    ENABLE_USER_SCRIPT_SANDBOXING: "NO"

packages:
  CatBoard:
    path: .
  TieredGridLayout:
    url: https://github.com/atrh95/tiered-grid-layout
    from: "1.2.0"
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher.git
    from: "8.3.2"
  # Add other necessary packages for CatBoard here

targets:
  CatBoardApp:
    type: application
    platform: iOS
    sources:
      - path: CatBoardApp
    dependencies:
      - package: CatBoard
        product: CatBoard
      - package: TieredGridLayout
        product: TieredGridLayout
      - package: Kingfisher
        product: Kingfisher
    settings:
      base:
        DEVELOPMENT_LANGUAGE: ja
        GENERATE_INFOPLIST_FILE: "YES"
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.CatBoardApp
        # Add other required iOS settings
    info:
      path: CatBoardApp/Info.plist
      properties:
        CFBundleName: $(PRODUCT_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleDisplayName: CatBoard
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIStatusBarStyle: UIStatusBarStyleDefault
        UIStatusBarHidden: false
        UIViewControllerBasedStatusBarAppearance: true
        UIRequiresFullScreen: false
        # Add other necessary plist keys

  # Logic modules are managed by SwiftPM, so no direct dependencies or sources are listed here.

  CatBoardTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: CatBoardTests
    dependencies:
      - target: CatBoardApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.CatBoardTests

  CatBoardUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: CatBoardUITests
    dependencies:
      - target: CatBoardApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.CatBoardUITests
        TEST_TARGET_NAME: CatBoardApp

schemes:
  CatBoardApp:
    build:
      targets:
        CatBoardApp: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: false
      targets:
        - CatBoardTests
        - CatBoardUITests

  CatBoardTests:
    build:
      targets:
        CatBoardTests: all
    test:
      config: Debug
      gatherCoverageData: false
      targets:
        - CatBoardTests

  CatBoardUITests:
    build:
      targets:
        CatBoardUITests: all
    test:
      config: Debug
      gatherCoverageData: false
      targets:
        - CatBoardUITests
