# $ mint run xcodegen generate

name: CatBoardApp
options:
  deploymentTarget:
    iOS: 17.0
  createIntermediateGroups: true

configs:
  Debug: debug
  Release: release

settings:
  base:
    SWIFT_VERSION: 5.9
    MARKETING_VERSION: 1.0
    CURRENT_PROJECT_VERSION: 1
    ENABLE_USER_SCRIPT_SANDBOXING: "NO"

packages:
  ScaryCatScreeningKit:
    url: https://github.com/atrh95/scary-cat-screening-kit
    from: "3.1.4"
  TieredGridLayout:
    url: https://github.com/atrh95/tiered-grid-layout
    from: "1.2.0"
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher.git
    from: "8.3.2"
  # Add other necessary packages for CatBoard here

targets:
  CatBoardApp:
    type: application
    platform: iOS
    sources:
      - path: CatBoardApp
    dependencies:
      - target: CatURLImageModel
      - target: CatImageURLRepository
      - target: CatImageLoader
      - target: CatImageScreener
      - target: CatImagePrefetcher
      - target: CatAPIClient
      - package: TieredGridLayout
        product: TieredGridLayout
      - package: Kingfisher
    settings:
      base:
        DEVELOPMENT_LANGUAGE: ja
        GENERATE_INFOPLIST_FILE: "YES"
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.CatBoardApp
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        # Add other required iOS settings
    info:
      path: CatBoardApp/Info.plist
      properties:
        CFBundleName: $(PRODUCT_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleDisplayName: CatBoard
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIStatusBarStyle: UIStatusBarStyleDefault
        UIStatusBarHidden: false
        UIViewControllerBasedStatusBarAppearance: true
        UIRequiresFullScreen: false
        # Add other necessary plist keys

  CatURLImageModel:
    type: framework
    platform: iOS
    sources:
      - path: CatURLImageModel
    settings:
      base:
        DEVELOPMENT_LANGUAGE: ja
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.CatBoard.CatURLImageModel
        TARGETED_DEVICE_FAMILY: "1,2"
        GENERATE_INFOPLIST_FILE: YES
        SKIP_INSTALL: "NO"

  CatAPIClient:
    type: framework
    platform: iOS
    sources:
      - path: CatAPIClient
    dependencies:
      - target: CatURLImageModel
    settings:
      base:
        DEVELOPMENT_LANGUAGE: ja
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.CatBoard.CatAPIClient
        TARGETED_DEVICE_FAMILY: "1,2"
        GENERATE_INFOPLIST_FILE: YES
        SKIP_INSTALL: "NO"

  CatImageURLRepository:
    type: framework
    platform: iOS
    sources:
      - path: CatImageURLRepository
    dependencies:
      - target: CatURLImageModel
      - target: CatAPIClient
    settings:
      base:
        DEVELOPMENT_LANGUAGE: ja
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.CatBoard.CatImageURLRepository
        TARGETED_DEVICE_FAMILY: "1,2"
        GENERATE_INFOPLIST_FILE: YES
        SKIP_INSTALL: "NO"

  CatImageLoader:
    type: framework
    platform: iOS
    sources:
      - path: CatImageLoader
    dependencies:
      - target: CatURLImageModel
      - target: CatImageURLRepository
      - target: CatImageScreener
      - package: Kingfisher
    settings:
      base:
        DEVELOPMENT_LANGUAGE: ja
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.CatBoard.CatImageLoader
        TARGETED_DEVICE_FAMILY: "1,2"
        GENERATE_INFOPLIST_FILE: YES
        SKIP_INSTALL: "NO"

  CatImageScreener:
    type: framework
    platform: iOS
    sources:
      - path: CatImageScreener
    dependencies:
      - target: CatURLImageModel
      - package: ScaryCatScreeningKit
    settings:
      base:
        DEVELOPMENT_LANGUAGE: ja
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.CatBoard.CatImageScreener
        TARGETED_DEVICE_FAMILY: "1,2"
        GENERATE_INFOPLIST_FILE: YES
        SKIP_INSTALL: "NO"

  CatImagePrefetcher:
    type: framework
    platform: iOS
    sources:
      - path: CatImagePrefetcher
    dependencies:
      - target: CatURLImageModel
      - target: CatImageLoader
      - package: Kingfisher
    settings:
      base:
        DEVELOPMENT_LANGUAGE: ja
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.CatBoard.CatImagePrefetcher
        TARGETED_DEVICE_FAMILY: "1,2"
        GENERATE_INFOPLIST_FILE: YES
        SKIP_INSTALL: "NO"

  CatBoardTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: CatBoardTests
    dependencies:
      - target: CatBoardApp
      - target: CatURLImageModel
      - target: CatImageScreener
      - target: CatImageLoader
      - target: CatAPIClient
      - target: CatImageURLRepository
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.CatBoardTests
        TARGETED_DEVICE_FAMILY: "1,2"
        GENERATE_INFOPLIST_FILE: NO

  CatBoardUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: CatBoardUITests
    dependencies:
      - target: CatBoardApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.CatBoardUITests
        TARGETED_DEVICE_FAMILY: "1,2"
        TEST_TARGET_NAME: CatBoardApp
        GENERATE_INFOPLIST_FILE: NO

schemes:
  CatBoardApp:
    build:
      targets:
        CatBoardApp: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: false
      targets:
        - CatBoardTests
        - CatBoardUITests

  CatBoardTests:
    build:
      targets:
        CatBoardTests: test
    test:
      config: Debug
      targets:
        - CatBoardTests

  CatBoardUITests:
    build:
      targets:
        CatBoardUITests: test
    test:
      config: Debug
      targets:
        - CatBoardUITests
