name: CatBoard CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


env:
  TEAM_ID: ${{ secrets.TEAM_ID }}
  APPLE_ID: ${{ secrets.APPLE_ID }}

jobs:
  # パッケージのテスト
  test-package:
    name: Test Package
    uses: ./.github/workflows/test-packages.yml

  # コード品質チェック
  code-quality:
    name: Code Quality Check
    uses: ./.github/workflows/code-quality.yml
    
  # ビルドとテスト
  build-and-test:
    name: Run Tests
    uses: ./.github/workflows/run-tests.yml
    
  # リリースビルド
  build-archive:
    name: Build Unsigned Archive
    uses: ./.github/workflows/build-unsigned-archive.yml
    secrets:
      TEAM_ID: ${{ secrets.TEAM_ID }}
      APPLE_ID: ${{ secrets.APPLE_ID }}