name: Run Tests

on:
  workflow_call:

jobs:
  build-for-testing:
    runs-on: macos-latest
    env:
      MINT_PATH: ${{ github.workspace }}/.mint
    steps:
      - uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Cache Mint packages
        uses: actions/cache@v4
        id: cache-mint-packages
        with:
          path: ${{ github.workspace }}/.mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-

      - name: Install Mint
        run: brew install mint

      - name: Generate Xcode Project
        run: mint run xcodegen generate

      - name: Build for Testing via Makefile
        run: make ci-build-for-testing # SIMULATOR_UDID is now handled by Makefile's select-simulator

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-products
          path: |
            ${{ github.workspace }}/ci-outputs/test-results/DerivedData/Build/Products/
          retention-days: 1

  unit-test:
    runs-on: macos-latest
    needs: build-for-testing
    env:
      MINT_PATH: ${{ github.workspace }}/.mint
    steps:
      - uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Cache Mint packages
        uses: actions/cache@v4
        id: cache-mint-packages
        with:
          path: ${{ github.workspace }}/.mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-

      - name: Install Mint
        run: brew install mint

      - name: Generate Xcode Project
        run: mint run xcodegen generate

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: built-products
          path: ${{ github.workspace }}/ci-outputs/test-results/DerivedData/Build/Products/

      - name: Run Unit Tests via Makefile
        id: unit_tests
        run: make ci-unit-test # SIMULATOR_UDID is now handled by Makefile's select-simulator

  ui-test:
    runs-on: macos-latest
    needs: build-for-testing
    env:
      MINT_PATH: ${{ github.workspace }}/.mint
    steps:
      - uses: actions/checkout@v4

      - name: Cache Mint packages
        uses: actions/cache@v4
        id: cache-mint-packages
        with:
          path: ${{ github.workspace }}/.mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-

      - name: Install Mint
        run: brew install mint

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Generate Xcode Project
        run: mint run xcodegen generate

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: built-products
          path: ${{ github.workspace }}/ci-outputs/test-results/DerivedData/Build/Products/

      - name: Run UI Tests via Makefile
        id: ui_tests
        run: make ci-ui-test # SIMULATOR_UDID is now handled by Makefile's select-simulator