name: Run Tests

on:
  workflow_call:
    outputs:
      test_result:
        description: "Test Result"
        value: ${{ jobs.report-status.outputs.test_result }}

jobs:
  unit-test:
    runs-on: macos-latest
    env:
      MINT_PATH: ${{ github.workspace }}/.mint
    outputs:
      result: ${{ steps.unit_tests.outcome }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache Mint packages
        uses: actions/cache@v4
        id: cache-mint-packages
        with:
          path: ${{ github.workspace }}/.mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-

      - name: Install Mint
        run: brew install mint

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Generate Xcode Project
        run: mint run xcodegen generate

      - name: Create Unit Test Output Directory
        run: mkdir -p ci-outputs/test-results/unit

      - name: Make find-simulator script executable
        run: chmod +x .github/scripts/find-simulator.sh

      - name: Select Simulator
        id: select_simulator
        run: |
          SIMULATOR_ID=$(./.github/scripts/find-simulator.sh)
          echo "シミュレータ ID ($SIMULATOR_ID) が選択されました"
          echo "simulator_id=$SIMULATOR_ID" >> $GITHUB_OUTPUT

      - name: Run Unit Tests
        id: unit_tests
        run: |
          set -o pipefail
          echo "シミュレータ ID (${{ steps.select_simulator.outputs.simulator_id }}) を使用してユニットテストを実行します"
          xcodebuild test \
            -project "CatBoardApp.xcodeproj" \
            -scheme "CatBoardTests" \
            -destination "platform=iOS Simulator,id=${{ steps.select_simulator.outputs.simulator_id }}" \
            -enableCodeCoverage NO \
            -resultBundlePath ./ci-outputs/test-results/unit/TestResults.xcresult \
            | xcbeautify --report junit --report-path ./ci-outputs/test-results/unit/junit.xml

      - name: Verify Unit Test Results
        if: steps.unit_tests.outcome == 'success'
        run: |
          echo "Checking for Unit Test results bundle..."
          RESULT_BUNDLE_PATH="./ci-outputs/test-results/unit/TestResults.xcresult"
          if [ ! -d "$RESULT_BUNDLE_PATH" ]; then
            echo "❌ Error: Unit test result bundle not found at $RESULT_BUNDLE_PATH"
            exit 1
          fi
          echo "✅ Unit test result bundle found at $RESULT_BUNDLE_PATH"

      - name: Upload Unit Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results-${{ github.run_id }}
          path: ci-outputs/test-results/unit
          retention-days: 1

  ui-test:
    runs-on: macos-latest
    env:
      MINT_PATH: ${{ github.workspace }}/.mint
    outputs:
      result: ${{ steps.ui_tests.outcome }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache Mint packages
        uses: actions/cache@v4
        id: cache-mint-packages
        with:
          path: ${{ github.workspace }}/.mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-

      - name: Install Mint
        run: brew install mint

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Generate Xcode Project
        run: mint run xcodegen generate

      - name: Create UI Test Output Directory
        run: mkdir -p ci-outputs/test-results/ui

      - name: Make find-simulator script executable
        run: chmod +x .github/scripts/find-simulator.sh

      - name: Select Simulator
        id: select_simulator
        run: |
          SIMULATOR_ID=$(./.github/scripts/find-simulator.sh)
          echo "シミュレータ ID ($SIMULATOR_ID) が選択されました"
          echo "simulator_id=$SIMULATOR_ID" >> $GITHUB_OUTPUT

      - name: Run UI Tests
        id: ui_tests
        run: |
          set -o pipefail
          echo "シミュレータ ID (${{ steps.select_simulator.outputs.simulator_id }}) を使用して UI テストを実行します"
          xcodebuild test \
            -project "CatBoardApp.xcodeproj" \
            -scheme "CatBoardUITests" \
            -destination "platform=iOS Simulator,id=${{ steps.select_simulator.outputs.simulator_id }}" \
            -enableCodeCoverage NO \
            -resultBundlePath ./ci-outputs/test-results/ui/TestResults.xcresult \
            | xcbeautify --report junit --report-path ./ci-outputs/test-results/ui/junit.xml

      - name: Verify UI Test Results
        if: steps.ui_tests.outcome == 'success'
        run: |
          echo "Checking for UI Test results bundle..."
          RESULT_BUNDLE_PATH="./ci-outputs/test-results/ui/TestResults.xcresult"
          if [ ! -d "$RESULT_BUNDLE_PATH" ]; then
            echo "❌ Error: UI test result bundle not found at $RESULT_BUNDLE_PATH"
            exit 1
          fi
          echo "✅ UI test result bundle found at $RESULT_BUNDLE_PATH"

      - name: Upload UI Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-results-${{ github.run_id }}
          path: ci-outputs/test-results/ui
          retention-days: 1

  report-status:
    needs: [unit-test, ui-test]
    runs-on: ubuntu-latest
    if: always()
    outputs:
      test_result: ${{ steps.set_status.outputs.result }}
    steps:
      - name: Check test job outcomes and set final status
        id: set_status
        run: |
          echo "Unit Test job outcome: ${{ needs.unit-test.outputs.result }}"
          echo "UI Test job outcome: ${{ needs.ui-test.outputs.result }}"
          if [[ "${{ needs.unit-test.outputs.result }}" == "success" && "${{ needs.ui-test.outputs.result }}" == "success" ]]; then
            echo "Both test jobs succeeded."
            echo "result=success" >> $GITHUB_OUTPUT
          else
            echo "One or both test jobs failed or were skipped."
            echo "result=failure" >> $GITHUB_OUTPUT
          fi