name: Test Packages

on:
  workflow_call:

jobs:
  test-package:
    runs-on: macos-14
    strategy:
      matrix:
        package: [CatImageURLRepository, CatImageScreener, CatImagePrefetcher]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: '5.9'

      - name: Cache Swift Package Dependencies
        uses: actions/cache@v4
        with:
          path: |
            .build
            Packages/CatImageScreener/.build
            Packages/CatImagePrefetcher/.build
            Packages/CatImageURLRepository/.build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.swift', '**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run Package Test for ${{ matrix.package }}
        run: make test-${{ matrix.package }}
